#!/usr/bin/env -S python3 -O

############################################################################
## Author: Frederic Depuydt                                               ##
## Mail: frederic.depuydt@outlook.com                                     ##
############################################################################

## INCLUDES
from depuydt import command, echo

echo.title("DOCKER PRUNE - Removing unnecessary containers, images, volumes and networks")
command.exec("docker container prune -f")
command.exec("docker image prune -f")
command.exec("docker volume prune -f")
command.exec("docker network prune -f")