#!/usr/bin/env python3

############################################################################
## Docker-Info                                                            ##
## Author: Frederic Depuydt                                               ##
## Mail: frederic.depuydt@outlook.com                                     ##
############################################################################

## INCLUDES
from depuydt.docker.deploy import Deploy

Deploy()